---
title: "Reproducible Research: Peer Assessment 1"

date: "Thursday, December 11, 2014"
output: html_document
---

```{r load packages, echo=TRUE, warning=FALSE}
# required packages
library(dplyr)
library(ggplot2)
library(xtable)
library(data.table)
```
## Loading and preprocessing the data
```{r load data, echo =TRUE, results='asis'}

##Download dataset
setwd("~/GitHub/RepData_PeerAssessment1")
#unzip("activity.zip")
#list.files()

Act.data<-read.csv("activity.csv")
```
## What is mean total number of steps taken per day?
```{r mean steps per day, echo=TRUE}
#group by table
xAct <- tbl_df(Act.data)
steps.per.day <- group_by(xAct, date)
steps.per.Int <- group_by(xAct, interval)

tot.steps.per.day <- summarize(steps.per.day, total = 
                                 sum(steps, na.rm = TRUE))
daily_mean <- mean(tot.steps.per.day$total, na.rm = TRUE)
daily_median <- median(tot.steps.per.day$total, na.rm = TRUE)

daily_mean      ## The mean total daily number of steps
daily_median    ##  The median total daily number steps 

```
```{r number of steps by 5 mint interval, echo=TRUE, fig.height= 6, fig.width= 10}
totstepsperint <- summarize(steps.per.Int, x_avg = mean(steps, na.rm = TRUE))

Interval_mean <- mean(summarize(steps.per.Int, x_avg = mean(steps, na.rm = TRUE))$x_avg, na.rm = TRUE)
Interval_mean

hist(tot.steps.per.day$total, breaks = 20, col = "blue", border = "black", 
     main = paste("Histogram of Daily Steps without replacing Missing vbalue"), ylab = "Frequency", xlab = "steps")


```

```{r echo=TRUE, fig.height=6, fig.width=10}

plot(totstepsperint$interval, totstepsperint$x_avg, type="l", xlab="Interval", ylab="Number of Steps", main = "Number of steps per 5 minutes interval")
totstepsperint[which(totstepsperint$x_avg==max(totstepsperint$x_avg)),]$interval -> max.steps.int

### Maxium nubmer step interval
max.steps.int

```       
## Imputing missing values

```{r replace missing value, fig.width=10, fig.height=6}
library(plyr)
impute.steps <- function(x) replace(x, is.na(x), ceiling(mean(x, na.rm = TRUE)))
xAct1<-ddply(xAct, ~interval, transform, steps = impute.steps(steps))

stepsperDay<-aggregate(xAct1$steps, by=list(xAct1$date), FUN=sum, na.rm=TRUE)
par(mar=c(8,2,2,2))

hist(stepsperDay$x, breaks = 20, col = "lightgreen", border = "green", 
     main = paste("Histogram of Daily Steps with imputing missing value"), ylab = "count", xlab = "steps")

### Mean and median total steps daily after imputing missing values
mean(stepsperDay$x) 
median(stepsperDay$x)

stepsperInterval<-aggregate(xAct1$steps, by=list(xAct1$interval), FUN=mean, na.rm=TRUE)
```
```{r timeseries plot, echo=TRUE}

plot(stepsperInterval$Group.1, stepsperInterval$x, type="l", xlab="Interval", ylab="Number of Steps")
##totstepsperint[which(totstepsperint$x_avg==max(totstepsperint$x_avg)),]$interval -> max.steps.int
##max.steps.int
```

## Are there differences in activity patterns between weekdays and weekends?
```{r}
library(lattice)
xAct1$date <- as.Date(xAct1$date, format="%Y-%m-%d")
xAct1$WDay <- weekdays(xAct1$date)
xAct1$dayType[xAct1$WDay=="Sunday"]<-"weekend"
xAct1$dayType[xAct1$WDay=="Saturday"]<-"weekend"
xAct1$dayType[is.na(xAct1$dayType)]<-"weekday"
xAct1$dayType<-as.factor(xAct1$dayType)
stepsper5<-aggregate(xAct1$steps, by=list(xAct1$interval, xAct1$dayType), FUN=mean, na.rm=TRUE)
xyplot(stepsper5$x~stepsper5$Group.1|stepsper5$Group.2, layout=c(1,2), type="l", xlab="Interval", ylab="Number of steps")
```